### ISSUE TITLE
get_example_data() always download

### ISSUE THREAD

**Issue by kauedesousa** [JGCRI/osiris#24]
This issue belongs to the review on JOSS https://github.com/openjournals/joss-reviews/issues/5226

The function `get_example_data()` always download the data even when it already exists in the directory. My suggestion is to dig into the function `geodata::gadm()` and check their approach to download the data only once even if you run the line of code many times. Additionally is nice to return a message highlighting the path where the folder was written. 

``` 
library("geodata")

gadm("ZWE", level=0, path = getwd())

```

**Comment by hahsan1** [comment]
Thank you for this suggestion. I have updated the `get_example_data()` function so that it now outputs a message to let the user know if the sample data is already installed. I also made it clear which path the data is installed to.
