### ISSUE TITLE
Avoid pipes %>% in functions

### ISSUE THREAD

**Issue by kauedesousa** [JGCRI/osiris#25]
This issue belongs to the review on JOSS openjournals/joss-reviews#5226

Pipes %>% are nice when writing scripts. For R packages is not. They are difficult to control inside a function and also increases the computational cost. Even the `tidyverse` friend package `sf` don't use it in their code https://github.com/r-spatial/sf/blob/main/R/tidyverse.R. Please remove the pipes.

**Comment by kauedesousa** [comment]
And it becomes really strange (and dangerous) when you assign all the initial objects as `.`

Like here   [NULL -> year -> value -> vtag -> units -> ctag -> type -> Scenario ->](https://github.com/JGCRI/osiris/blob/a54410f4a6a685585ec084cf0a42cf969d42357f/R/grid_to_basin_yield.R#L58)

**Comment by hahsan1** [comment]
> This issue belongs to the review on JOSS [openjournals/joss-reviews#5226](https://github.com/openjournals/joss-reviews/issues/5226)
> 
> Pipes %>% are nice when writing scripts. For R packages is not. They are difficult to control inside a function and also increases the computational cost. Even the `tidyverse` friend package `sf` don't use it in their code https://github.com/r-spatial/sf/blob/main/R/tidyverse.R. Please remove the pipes.

We appreciate your comments regarding the use of pipes in our functions. You bring up a good point about increase in computational cost. However, we believe that the use of pipes greatly improves the readability and flow of the code. Without the pipes, the code would be overly verbose and difficult to follow. We believe keeping the code readable and accessible to humans is an important factor to consider besides the pure computational aspects.

**Comment by hahsan1** [comment]
> And it becomes really strange (and dangerous) when you assign all the initial objects as `.`
> 
> Like here [NULL -> year -> value -> vtag -> units -> ctag -> type -> Scenario ->](https://github.com/JGCRI/osiris/blob/a54410f4a6a685585ec084cf0a42cf969d42357f/R/grid_to_basin_yield.R#L58)

Here we are actually assigning `NULL` to these objects during the initializing step.
